adding and configuring  user location o map
CapistranoIFCE/social_map pull request #14
Opened 2022-09-12 14:28 UTC by rainarodrigues

#2 The User Location on a Map feature was created, with user privacy permissions options within the app.

2022-09-12 16:49 UTC, ThiagoHBA requested changes

2022-09-12 16:49 UTC, ThiagoHBA commented on SocialMap/Source/View/Core/UserFeed/UserFeedView.swift
> +        MapView ( coordinate: controller.userLocation?.center ?? CLLocationCoordinate2D(latitude: 3.01, longitude: 4.0))
Usar o .init() igual o código que o @CapistranoIFCE tinha feito aqui vai melhorar na leitura

2022-09-13 11:43 UTC, daneccc requested changes

2022-09-13 11:43 UTC, daneccc commented on SocialMap/Source/View/Core/UserFeed/ MockedPinView.swift
> +//
remove header comments

2022-09-13 12:20 UTC, rainarodrigues commented on SocialMap/Source/View/Core/UserFeed/UserFeedView.swift
> +        MapView ( coordinate: controller.userLocation?.center ?? CLLocationCoordinate2D(latitude: 3.01, longitude: 4.0))
Adicionado

2022-09-13 12:20 UTC, rainarodrigues commented on SocialMap/Source/View/Core/UserFeed/ MockedPinView.swift
> +//
Removido

2022-09-13 12:24 UTC, merged